config/routes.rb
Rails.application.routes.draw do
  resources(:hosts, except: [:edit,:update,:destroy, :create])

  root 'hosts#index'

end

app/models/host.rb
class Host < ActiveRecord::Base
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :address, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true
  validates :phone, presence: true
  validates :capacity, presence: true
  validates :sleeping, presence: true

  def name
  	"#{firstname} #{lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :set_host, only: [:show, :edit, :update, :destroy]

  # GET /hosts
  # GET /hosts.json
  def index
    @hosts = Host.all
  end

  # GET /hosts/1
  # GET /hosts/1.json
  def show
    redirect_to root_path if @host.id != session[:id]
  end

  # GET /hosts/new
  def new
    @host = Host.new
  end

  # GET /hosts/1/edit
  def edit
  end

  # POST /hosts
  # POST /hosts.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_host
      @host = Host.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def host_params
      params.require(:host).permit(:firstname, :lastname, :address, :zipcode, :city, :phone, :capacity, :comments, :email, :sex, :beenhost, :animales, :sleeping, :isstudent, :extraday, :Onedayearly)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/views/hosts/_form.html.erb
<div class ="container">
    <div class='row newhost'>

      <div class='col-md-3 padding-cheat'>

        <%= bootstrap_form_for(@host) do |f| %>

        <% end %>
    </div>


    <div class='col-md-7'>
        <div class='forminfo bigtext2'>
            <h1>Vi har nok verter</h1>
            <p>Så bra du har lyst til å være vert. Vi er nå fylt opp, og har derfor ikke behov for flere verter.</p>
            <p>Om du er vert allerede, og har noen spørsmål så er det bare å ta kontakt på verter@isfit.org</p>
              <p><%= link_to 'Tilbake til forsiden', root_path, class: 'btn btn-large btn-primary' %></p>
      </div>
      </div>  
  </div>
</div>

app/views/hosts/index.html.erb
<div id="content-wrapper">

  <section id="welcome">
    <div class="container">
      <div class="row">
        <div class="col-md-9 forside">
          <div class="bigtext" >
            <h1>Verdt å være vert!</h1>
          </div>
        </div>
        <div class="col-md-3 sidebar visible-lg">
          <nav role="navigation">
            <ul class="nav nav-left" id="test">
              <li class="sidebar-link"><a href="#welcome"></i><b>Verdt å være vert</b></a></li>
              <li class="sidebar-link"><a href="#become"></i><b>Bli vert</b></a></li>
              <li class="sidebar-link"><a href="#what"></i><b>Hva er egentlig dette?</b></a></li>
              <li class="sidebar-link"><a href="#why"></i><b>Hvorfor skal jeg bli vert?</b></a></li>
              <li class="sidebar-link"><a href="#do"></i><b>Hva må jeg gjøre?</b></a></li>
              <li class="sidebar-link"><a href="#strikk"></i><b>Strikk til ISFiT</b></a></li>
              <li class="sidebar-link"><p href="#btn_side"></i><b> <%= link_to "Registrer deg her", new_host_path, class: "btn btn-primary" %></b></p></li>
            </ul>
          </nav>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <div class="row">
            <blockquote style="margin-top: 300px; background-color:rgba(204, 204, 204, 0.6);" class="col-md-12">
              <p>Jeg har hatt personer fra Rwanda, USA, Israel, Tyrkia og fra det tidligere Jugoslavia boende hos meg. Det har alltid vært en artig opplevelse. Man får møte folk fra andre kulturer og høre hva de tenker om sitt hjemland, og ikke minst hva de synes om oss nordmenn.</p>
              <small>Trygve Bragstad, 5. gang ISFiT-vert</small>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </section> 



    <section id="become">
      <div class="container">
        <div class="row">
          <div class="col-md-4 bigtext">
            <h2><%= link_to "Jeg vil bli vert!", new_host_path, class: 'vert-button' %></h2>
            <p>Du kan registrere deg helt frem til <span class="special">4. februar 2015</span>. Å være vert er verdt det!</p>
            <p>Har du spørsmål om å være vert?<br>
              Send en e-post til <a class="vert-button" href="mailto:verter@isfit.org">verter@isfit.org</a></p>
              <%= link_to "Registrer deg her", new_host_path, class: "btn btn-large btn-primary" %>
            </div>
            <div class="col-md-5 visible-lg">
              <!--<%= image_tag("workshop.jpg",:class => "graphic2", width: '100%')%>-->
              <iframe class="graphic" width="420" height="315" src="//www.youtube.com/embed/B9wVW6IXZY4" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
      </div>
    </section>



    <section id="what">
      <div class="container">
        <div class="row">
          <div class="col-md-9">
            <div class = "bigtext">
              <h1>Hva er egentlig dette?</h1>
              <p>ISFiT arrangeres annethvert år, og hver festival har et tema av sosial og politisk karakter med internasjonal relevans. Teamet for ISFiT 2015 er korrupsjon, og festivalen finner sted i Trondheim 5.-15. februar. Her møtes over 450 studenter fra hele verden for å diskutere temaet i 17 ulike workshoper, og for å ta del i festivalens kulturprogram. ISFiT er en ideell organisasjon og arrangeres ved hjelp av innsatsen til over 400 engasjerte Trondheimsstudenter.</p>
            </div>
            <div style="text-align: center;">
             <!-- <iframe width="420" height="315" src="//www.youtube.com/embed/fNVuKXrFItI" frameborder="0" allowfullscreen></iframe>-->
              <%= image_tag("workshop.jpg", width: '50%')%>
            </div>
            <div class = "bigtext">
              <p>For å gjennomføre ISFiT trenger vi 450 sengeplasser, og vi er helt avhengig av Trondheims mange husrom og snille sjeler som vil la en student bo hos dem i 10 dager.</p>
            </div>
          </div>
        </div>
      </div>
    </section>





    <section id="why">
      <div class="container">
        <h1 class="big">
          Hvorfor skal jeg bli vert?
        </h1>
        <div class="row">
          <div class="col-md-3 bigtext">
            <%= image_tag("kultur.jpg", width: '100%', class: 'visible-lg')%>
            <h1 class="center">Møt en ny kultur</h1>
            <p class="center">I februar samler vi hele verden i Trondheim, dette er din sjanse til å oppleve noe annerledes.</p>
          </div>
          <div class="col-md-3 bigtext">
            <%= image_tag("venn.jpg", width: '100%', class: 'visible-lg')%>
            <h1 class="center">Få en venn for livet</h1>
            <p class="center">Her er mulighetene mange til å stifte unike vennskap. Kanskje får du en framtidig statsleder sovende på din sofa?</p>
          </div>
          <div class="col-md-3 bigtext">
            <%= image_tag("eventyr.jpg", width: '100%', class: 'visible-lg')%>
            <h1 class="center">Vinterens eventyr</h1>
            <p class="center">Oppleve en februar du aldri vil glemme, og hjelp oss gjøre ISFiT mulig!</p>
          </div>
        </div>
      </div>
    </section>

    <section id="do">
      <div class="container">
        <h1 class="big">
          Hva må jeg gjøre?
        </h1>
        <div class="row">
          <div class="col-md-4 center bigtext ">
            <%= image_tag("Sengen.gif",:class => "round", width: '100%', class: 'visible-lg')%>
            <h1 class="center">Seng</h1>
            <p class="bigtext">Alt du trenger er en ekstra seng, sofa eller kun gulvplass, så stiller vi med madrassen(e).</p>
          </div>
          <div class="col-md-1">
          </div>
          <div class="col-md-4 center bigtext ">
            <%= image_tag("Frokost.gif",:class => "round", width: '100%', class: 'visible-lg')%>
            <h1 class="center">Frokost</h1>
            <p class="bigtext">Du stiller med en enkel frokost, vi dekker alle andre måltider.</p>
          </div>
          <div class="col-md-9">
            <p class="big ">Deltakerne er opptatt mesteparten av dagen, med workshop på dagtid og kulturprogram på kvelden.</p>
          </div>
        </div>
      </div>
    </section>

    <section id="strikk">
      <div class="container">
        <div class="row">
          <h1 class="big">Varm en deltaker – strikk til ISFiT 2015!</h1>
        </div>
        <div class="row">
          <div class="col-md-4 bigtext">
            <p>ISFiT er en ideell organisasjon og arrangeres ved hjelp av innsatsen til over 400 engasjerte Trondheimsstudenter. I den anledning har vi designet strikkemønster som en kan strikke, og etterhvert levere inn til oss. Finn fram pinner og garn! Aktiviser og rekrutter hele familien fra oldemor til pusekatt! Sammen skal vi klare å strikke nok til å holde alle varme, og gi hver og en et håndfast minne for livet.
            </p>
          </div>
          <div class="col-md-5 visible-lg">
            <%= image_tag("strikk.jpg", width: '100%')%>
          </div>
        </div>
        <br>
        <br>
        <div class="row">
          <div class="col-md-4">
            <p class="big">På facebook kan man bli medlem i en gruppe for å få mer informasjon, hjelp med strikking eller for å dele sine bidrag.</p>
            <%= link_to "Til facebookgruppen", "https://www.facebook.com/groups/863800783650227/?fref=ts", class: "btn btn-primary" %>
          </div>
          <div class="col-md-5">

            <p class="big">Strikkeoppskriftene kan du finne her:</p>
            <%= link_to "Votter", "http://www.ravelry.com/patterns/library/isfitstrikk-votter-mittens", class: "btn btn-primary" %>
            <%= link_to "Sokker", "http://www.ravelry.com/patterns/library/isfitstrikk-sokker-socks", class: "btn btn-primary" %>
            <%= link_to "Lue", "http://www.ravelry.com/patterns/library/isfitstrikk-lue-hat", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </section>


  </div> <!-- End content wrapper -->

app/views/hosts/new.html.erb
<div id = "content-wrapper" class="container">
    <div class="col-md-12">
      <%= render 'form' %>
    </div>

  </div>

</div>

app/views/hosts/show.html.erb
<div class="container newhost" id = "content-wrapper">
  <div class = "col-md-6 bigtext">
    <div class="alert alert-success" role="alert"><p><b>Du er registrert!</b> Du vil nå motta en mail innen kort tid med mer informasjon.</p></div>
    <p id="notice"><%= notice %></p>
    <p><b>Navn: </b><%= @host.firstname %> <%= @host.lastname %> </p>
    <p><b>Epost: </b><%= @host.email %> </p>
    <p><b>Telefonnummer: </b><%= @host.phone %> </p>
    <p><b>Adresse: </b><%= @host.address %>, <%= @host.zipcode %>, <%= @host.city %></p>
    <p><b>Har vært vert: </b>  
      <% if @host.beenhost %>
        Ja
      <% else %>
        nei
      <% end %></p>

    <p><b>Er student: </b>  
      <% if @host.isstudent %>
        Ja
      <% else %>
        nei
    <% end %></p>

    <p><b>Kan være vert en ekstra dag: </b>  
      <% if @host.extraday %>
        Ja
      <% else %>
        nei
    <% end %></p>

    <p><b>Har dyr: </b>  
      <% if @host.animales %>
        Ja
      <% else %>
        nei
    <% end %></p>
    <p><b>Overnattingsmuligheter:</b>
      <% if @host.sleeping.eql? 0 %>
        Sofa
      <% elsif @host.sleeping.eql? 1 %>
        Seng
      <% else %> 
        Trenger å låne madrass
      <% end %></p>

    <p><b>Kapasitet: </b><%= @host.capacity %> </p>
    <p><b>Kjønn:</b>
      <% if @host.sex.eql? 0 %>
        Ingen kjønn er foretrukket
      <% elsif @host.sex.eql? 1 %>
        Kvinne
      <% else %> 
        Mann
      <% end %></p>
    <p><b>Kommentarer: </b><%= @host.comments %> </p>

    <p><%= link_to 'Tilbake til forsiden', root_path, class: 'btn btn-primary btn-lg' %></p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bli vert - ISFiT 2015</title>
   <meta property="og:title" content="Bli vert! - ISFIT 2015"/>
    <meta property="og:type" content="non_profit"/>
    <meta property="og:image" content="<%= asset_path("venn.jpg") %>"/>
    <meta property="og:url" content="http://vert.isfit.org/"/>
    <meta property="og:site_name" content="ISFiT 2015"/>
    <meta property="fb:app_id" content="111446192243028"/>
    <meta property="og:description" content="5. til 15. februar kommer 450 studenter til Trondheim. De trenger et sted å bo."/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body data-spy="scroll">
    <%= yield %>
    <footer id="bottom-footer">
        <a href="http://isfit.org"><img alt="Isfitliten" class="footer-logo" src="http://i.imgur.com/zobJT.png"></a>
        <p>
        All written material and the ISFiT logo is copyrighted the ISFiT Foundation © 2015. Photos accredited to <a href="http://fg.samfundet.no">Fotogjengen</a>.
        </p>
      </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

   <!-- <script>
      $(document).ready(function() {
        $("#infofilm").fitVids();
        $.doTimeout(500, function() {
          $("#promo-text").removeClass("hidden").addClass("animated bounceInDown");
        });
        
      })
    </script>-->
  </div>
</body>
</html>